name: Lint, Build & Test

on:
  push:
    branches:
      - ${{ github.ref == 'refs/heads/main' && github.ref != 'refs/heads/${{ default-branch }}' || default-branch }} 
  pull_request:
    branches:
      - ${{ github.ref == 'refs/heads/main' && github.ref != 'refs/heads/${{ default-branch }}' || default-branch }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  lint-build-test:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/layerzero-labs/devcon:1.1.4-bookworm
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      options: --privileged
    env:
      HOME: /root

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Initialize docker services
        run: |
          umount /var/run/docker.sock || true
          /usr/local/share/docker-init.sh

      - name: Yarn install
        run: |
          yarn install --immutable

      - name: Build
        run: |
          yarn build

      - name: Run Tests
        run: |
          yarn test
